export default [
  {
    milestone: 'A rough start',
    milestone_type: 'game',
    date: 'Feb. 5, 1999',
    opponent: 'Seattle',
    note: 'Nowitzki’s debut wasn’t exactly a preview of what was to come. In just 16 minutes, he went 0-for-5 from the field, finishing with just two points.',
    milestone_id: 29800012,
  },
  {
    milestone: 'First field goal',
    milestone_type: 'shot',
    date: 'Feb. 7, 1999',
    opponent: 'Golden State',
    note: 'Two nights after he debuted with an 0-for from the field, Nowitzki scored his first field goal, a 16-foot jumper from the right baseline. He finished the night with 16 points.',
    milestone_id: 5,
  },
  {
    milestone: 'Career high',
    milestone_type: 'game',
    date: 'Dec. 2, 2004',
    opponent: 'Houston Rockets',
    note: 'Nowitzki scored a career-high 53 in a 113-106 win against the Rockets in 2004. He finished the night 15-for-32 from the field and 21-for-22 from the free throw line.',
    milestone_id: 20400222,
  },
  {
    milestone: '10,000th points',
    milestone_type: 'shot',
    date: 'Jan. 18, 2005',
    opponent: 'Washington',
    note: 'Nowitzki notched his 10,000 point with a 23-foot jumper against the Washington Wizards, becoming the fifth (and last) Maverick to reach that milestone.',
    milestone_id: 8146,
  },
  {
    milestone: '2006 Western Conference Semifinals',
    milestone_type: 'shot',
    date: 'May 22, 2006',
    opponent: 'San Antonio Spurs',
    note: 'In Game 7 of the Western Conference semifinals, Nowitkzi delievered a driving layup against Bruce Bowen and Manu Ginobli, drawing a foul. He nailed the free throw, sending the game to overtime.',
    milestone_id: 10954,
  },
  {
    milestone: '20,000 points',
    milestone_type: 'shot',
    date: 'Jan. 13, 2010',
    opponent: 'Los Angeles Lakers',
    note: 'Nowitzki reached 20,000 points with a 13-foot jumper over Los Angeles Lakers’ forward Lamar Odom in 2010. He’s the only Maverick to ever reach the mark.',
    milestone_id: 16509,
  },
  {
    milestone: '2011 NBA Finals',
    milestone_type: 'games',
    date: 'TK',
    opponent: 'Miami Heat',
    note: 'TK',
    milestone_id: [41000401, 41000406],
  },
  {
    milestone: 'Final layup of Game 6 of the 2011 Finals',
    milestone_type: 'shot',
    date: 'June 12, 2011',
    opponent: 'Miami Heat',
    note: 'Dirk put the finishing touches on the Mavericks’ first NBA Championship, scoring the team’s final field goal with 31 seconds left in Game 6 of the NBA Finals.',
    milestone_id: 18984,
  },
  {
    milestone: '30,000 points',
    milestone_type: 'shot',
    date: 'March 7, 2017',
    opponent: 'Los Angeles Lakers',
    note: 'Dirk scored his 30,000th point with a fadeaway jumper from the right baseline over the Lakers’ Larry Nance Jr., becoming the sixth player to join the 30,000 point club.',
    milestone_id: 25018,
  },
  {
    milestone: 'Passing Wilt',
    milestone_type: 'shot',
    date: 'March 18, 2019',
    opponent: 'New Orleans Pelicans',
    note: 'Nowitzki scored his 31,420th point with a fadeaway jumper from the top of the key over the Pelicans’ Kenrich Williams, passing Wilt Chamberlain to become the No. 6 scorer in NBA history.',
    milestone_id: 26229,
  },
  {
    milestone: 'Final home game?',
    milestone_type: 'game',
    date: 'April 9, 2019',
    opponent: 'Phoenix Suns',
    note: 'Nowitzki saved his best for his last home game at the American Airlines Center, scoring a season-high 30 points on 11-of-31 shooting, including five 3-pointers.',
    milestone_id: 21801216,
  },
];
