export default [
  ['SEA', 'Seattle SuperSonics'],
  ['GSW', 'Golden State Warriors'],
  ['SAS', 'San Antonio Spurs'],
  ['UTA', 'Utah Jazz'],
  ['HOU', 'Houston Rockets'],
  ['DEN', 'Denver Nuggets'],
  ['VAN', 'Vancouver Grizzlies'],
  ['POR', 'Portland Trailblazers'],
  ['LAL', 'Los Angeles Lakers'],
  ['LAC', 'Los Angeles Clippers'],
  ['PHX', 'Phoenix Suns'],
  ['ATL', 'Atlanta Hawks'],
  ['SAC', 'Sacramento Kings'],
  ['ORL', 'Orlando Magic'],
  ['NJN', 'New Jersey Nets'],
  ['DET', 'Detroit Pistons'],
  ['MIN', 'Minnesota Timberwolves'],
  ['MIA', 'Miami Heat'],
  ['CHI', 'Chicago Bulls'],
  ['CHH', 'Charlotte Hornets'],
  ['NYK', 'New York Knicks'],
  ['CLE', 'Cleveland Cavaliers'],
  ['MIL', 'Milwaukee Bucks'],
  ['TOR', 'Toronto Raptors'],
  ['WAS', 'Washington Wizards'],
  ['PHI', 'Philadelphia 76ers'],
  ['IND', 'Indiana Pacers'],
  ['BOS', 'Boston Celtics'],
  ['MEM', 'Memphis Grizzlies'],
  ['NOH', 'New Orleans Hornets'],
  ['CHA', 'Charlotte Bobcats'],
  ['OKC', 'Oklahoma City Thunder'],
  ['BKN', 'Brooklyn Nets'],
  ['NOP', 'New Orleans Pelicans'],
];
